### ISSUE TITLE
copy Function Protocol

### ISSUE THREAD

**Issue by Krieger-sch** [grelleum/snmp_tool#3]
I really like this library, excellent work and really clean.

I noticed that when you run something like "snmp.copy("running", "startup")", you get an error stating that "protocol" is used prior to it being defined. If you add "protocol=None" to the definition of the copy function you get rid of this problem and don't affect functionality.

Again, great library. Thank you.

**Comment by grelleum** [comment]
Thanks - this sounds like something I can fix in the code easily enough.  However, if you want to make a pull request with the fix, I would be happy to accept that.

**Comment by grelleum** [comment]
Merged pull request - thank you.
